import os
import socket
import secrets
from pathlib import Path
from typing import Optional, List
from pydantic_settings import BaseSettings

_ENV_PREFIX = "DOCKLINER_"


def _env(name: str, default: Optional[str] = None) -> Optional[str]:
    return os.environ.get(f"{_ENV_PREFIX}{name}", default)


def _log_stuck(message: str) -> None:
    """Append a startup issue to why_stuck.log."""
    from datetime import datetime
    log_path = Path("why_stuck.log")
    try:
        with log_path.open("a", encoding="utf-8") as f:
            f.write(f"[{datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')}] {message}\n")
    except Exception:
        pass


def _log_login(line: str) -> None:
    """Append a login event to login_attempts.log."""
    from datetime import datetime
    log_path = Path("login_attempts.log")
    try:
        with log_path.open("a", encoding="utf-8") as f:
            f.write(f"[{datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')}] {line}\n")
    except Exception:
        pass


def _ua_prefix(user_agent: str) -> str:
    """Return a 16-char blake3 prefix of the user agent for indexing."""
    from blake3 import blake3
    return blake3(user_agent.encode("utf-8")).hexdigest(length=8)


def log_login_attempt(user: str, ip: str, user_agent: str) -> None:
    ua = user_agent or ""
    _log_login(f"LOGIN_ATTEMPT user={user} ip={ip} ua_prefix={_ua_prefix(ua)} ua={ua}")


def log_login_success(user: str, ip: str, user_agent: str) -> None:
    ua = user_agent or ""
    _log_login(f"LOGIN_SUCCESS user={user} ip={ip} ua_prefix={_ua_prefix(ua)}")


def log_login_failure(user: str, ip: str, user_agent: str, reason: str = "bad_password") -> None:
    ua = user_agent or ""
    _log_login(f"LOGIN_FAILURE user={user} ip={ip} ua_prefix={_ua_prefix(ua)} reason={reason}")


def _write_env_value(key: str, value: str) -> None:
    """Update or append a single variable in .env without touching other lines."""
    env_path = Path(".env")
    prefix = f"{_ENV_PREFIX}{key}"
    line = f"{prefix}={value}"
    try:
        if env_path.exists():
            text = env_path.read_text(encoding="utf-8")
            lines = text.splitlines()
            found = False
            new_lines = []
            for ln in lines:
                stripped = ln.strip()
                if stripped.startswith(prefix) and ("=" in stripped or stripped == prefix):
                    new_lines.append(line)
                    found = True
                else:
                    new_lines.append(ln)
            if not found:
                new_lines.append(line)
            env_path.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
        else:
            env_path.write_text(f"# Auto-generated by DockLiner on startup\n{line}\n", encoding="utf-8")
    except Exception as e:
        _log_stuck(f"Could not write {prefix} to .env: {e}")


def _ensure_secret_key() -> None:
    """If SECRET_KEY is the placeholder, generate a random 256-bit key and write it."""
    if settings.SECRET_KEY and settings.SECRET_KEY != "change-me":
        return
    new_key = secrets.token_hex(32)  # 256 bits = 64 hex chars
    _write_env_value("SECRET_KEY", new_key)
    os.environ[f"{_ENV_PREFIX}SECRET_KEY"] = new_key
    # update settings in-place
    try:
        settings.__dict__["SECRET_KEY"] = new_key
    except Exception:
        pass
    _log_stuck(f"Generated new DOCKLINER_SECRET_KEY and wrote it to .env")


def _is_prime(n: int) -> bool:
    if n < 2:
        return False
    if n % 2 == 0:
        return n == 2
    r = int(n ** 0.5)
    for i in range(3, r + 1, 2):
        if n % i == 0:
            return False
    return True


def _allowed_ports() -> List[int]:
    """Return the configured allowed ports whitelist, defaulting to prime 50xxx list."""
    raw = os.environ.get(f"{_ENV_PREFIX}ALLOWED_PORTS", "")
    if not raw:
        raw = "50021,50023,50033,50047,50051,50053,50069,50077,50087,50093,50101,50111,50119,50123"
    ports = []
    for part in raw.split(","):
        part = part.strip()
        if not part:
            continue
        try:
            ports.append(int(part))
        except ValueError:
            _log_stuck(f"Invalid port in DOCKLINER_ALLOWED_PORTS: {part}")
    return ports


def is_port_free(host: str, port: int) -> bool:
    """Return True if the given host/port is free to bind."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.settimeout(0.5)
        try:
            s.bind((host, port))
            return True
        except OSError:
            return False


def _try_port(hosts: List[str], port: int) -> bool:
    """Return True if the port is free on every listed host."""
    for host in hosts:
        if not is_port_free(host, port):
            return False
    return True


class Settings(BaseSettings):
    # ------------------------------------------------------------------
    # Database configuration (new DB_MODE / DB_TYPE model)
    # ------------------------------------------------------------------
    # Legacy direct URL still wins if explicitly provided.
    DATABASE_URL: Optional[str] = None

    # auto | test | live
    DB_MODE: str = "auto"

    # sqlite | mysql | postgres  (only meaningful when DB_MODE is not auto,
    # or when auto resolution is ambiguous)
    DB_TYPE: str = "sqlite"

    # Live / test connection variables.
    DB_LIVE_HOST: str = "localhost"
    DB_LIVE_PORT: Optional[int] = None
    DB_LIVE_USER: str = ""
    DB_LIVE_PASSWORD: str = ""
    DB_LIVE_NAME: str = "dockliner"

    DB_TEST_HOST: str = "localhost"
    DB_TEST_PORT: Optional[int] = None
    DB_TEST_USER: str = ""
    DB_TEST_PASSWORD: str = ""
    DB_TEST_NAME: str = "dockliner_test"

    # Driver hints
    DB_DRIVER: str = "pymysql"           # pymysql (mysql) or psycopg2 (postgres)

    # SQLite-specific
    DB_PATH: str = "./dockliner.db"      # legacy fallback / default live sqlite path
    SQLITE_DB_PATH: str = "./dockliner.db"
    SQLITE_DB_NAME: str = "dockliner"
    SQLITE_TEST_DB_PATH: str = "./dockliner_test.db"

    # ------------------------------------------------------------------
    # Application directories & runtime
    # ------------------------------------------------------------------
    PROJECTS_DIR: str = "./projects"
    DOWNLOADS_DIR: str = "./downloads"
    LOGS_DIR: str = "./logs"
    SECRET_KEY: str = "change-me"
    HOST: str = "0.0.0.0"
    PORT: int = 50021                    # "50 first prime" default port
    PORT_SELECTION: str = "strict"       # strict | auto
    ALLOWED_PORTS: str = "50021,50023,50033,50047,50051,50053,50069,50077,50087,50093,50101,50111,50119,50123"
    MAX_ACCESS_TOKENS: int = 10
    SERVICE: str = "dockliner"
    DOCKER_EXECUTABLE: Optional[str] = None

    ERROR_API_TOKEN: Optional[str] = None
    # Default users as JSON array of {"user":"...","hash":"..."}
    # Passwords must be BLAKE3 512-bit hex hashes (128 hex chars).
    # Example: echo -n 'qwer.1234' | b3sum -l 64
    USERS: str = '[{"user":"root","hash":"9aa0a2b0f48247f8be3983b37fdbc13a4128da84d4a68ff6690d0202d8883c926f258640f9d8fad34f4b625043195da367307f04274618e734f7b5bf5641a663"}]'
    # DockLiner system version. Single source of truth for the running app.
    VERSION: str = "0.0.1"

    class Config:
        env_file = ".env"
        env_prefix = _ENV_PREFIX
        extra = "ignore"


# settings is re-instantiated after env-file guard below
# ---------------------------------------------------------------------------
# Database resolution helpers
# ---------------------------------------------------------------------------
def _has_live_vars(prefix: str = "DB_LIVE_") -> bool:
    return any(
        os.environ.get(f"{_ENV_PREFIX}{prefix}{k}")
        for k in ("HOST", "USER", "PASSWORD", "NAME")
    )


def _has_test_vars(prefix: str = "DB_TEST_") -> bool:
    return any(
        os.environ.get(f"{_ENV_PREFIX}{prefix}{k}")
        for k in ("HOST", "USER", "PASSWORD", "NAME")
    )


def resolve_db_mode() -> str:
    """Return concrete DB_MODE: live | test, resolving auto if needed."""
    mode = (settings.DB_MODE or "auto").lower().strip()
    if mode not in ("auto", "test", "live"):
        raise ValueError(f"DOCKLINER_DB_MODE must be auto, test, or live. Got: {settings.DB_MODE}")
    if mode == "auto":
        if _has_live_vars():
            return "live"
        if _has_test_vars():
            return "test"
        return "test"
    return mode


def resolve_db_type(mode: Optional[str] = None) -> str:
    """Return concrete DB_TYPE for the current mode, defaulting to sqlite."""
    requested = (settings.DB_TYPE or "sqlite").lower().strip()
    valid = {"sqlite", "mysql", "postgres", "postgresql"}
    if requested not in valid:
        raise ValueError(f"DOCKLINER_DB_TYPE must be one of {valid}. Got: {settings.DB_TYPE}")
    concrete_mode = mode or resolve_db_mode()
    # live/test only matters for initialization / validation; type is independent.
    if concrete_mode in ("test", "live") and requested == "sqlite":
        return "sqlite"
    return requested


def build_database_url(mode: Optional[str] = None, db_type: Optional[str] = None) -> str:
    """Build SQLAlchemy URL from settings, honoring DB_MODE/DB_TYPE."""
    if settings.DATABASE_URL:
        return settings.DATABASE_URL

    concrete_mode = mode or resolve_db_mode()
    concrete_type = db_type or resolve_db_type(concrete_mode)

    if concrete_mode == "test" and concrete_type == "sqlite":
        path = settings.SQLITE_TEST_DB_PATH
        return f"sqlite:///{path}"

    if concrete_type == "sqlite":
        path = settings.SQLITE_DB_PATH or settings.DB_PATH
        return f"sqlite:///{path}"

    if concrete_type == "mysql":
        host = settings.DB_LIVE_HOST if concrete_mode == "live" else settings.DB_TEST_HOST
        port = settings.DB_LIVE_PORT if concrete_mode == "live" else settings.DB_TEST_PORT
        user = settings.DB_LIVE_USER if concrete_mode == "live" else settings.DB_TEST_USER
        password = settings.DB_LIVE_PASSWORD if concrete_mode == "live" else settings.DB_TEST_PASSWORD
        db_name = settings.DB_LIVE_NAME if concrete_mode == "live" else settings.DB_TEST_NAME
        port = port or 3306
        driver = settings.DB_DRIVER if settings.DB_DRIVER and "mysql" in settings.DB_DRIVER else "pymysql"
        return f"mysql+{driver}://{user}:{password}@{host}:{port}/{db_name}"

    if concrete_type in ("postgres", "postgresql"):
        host = settings.DB_LIVE_HOST if concrete_mode == "live" else settings.DB_TEST_HOST
        port = settings.DB_LIVE_PORT if concrete_mode == "live" else settings.DB_TEST_PORT
        user = settings.DB_LIVE_USER if concrete_mode == "live" else settings.DB_TEST_USER
        password = settings.DB_LIVE_PASSWORD if concrete_mode == "live" else settings.DB_TEST_PASSWORD
        db_name = settings.DB_LIVE_NAME if concrete_mode == "live" else settings.DB_TEST_NAME
        port = port or 5432
        driver = settings.DB_DRIVER if settings.DB_DRIVER and "psycopg" in settings.DB_DRIVER else "psycopg2"
        return f"postgresql+{driver}://{user}:{password}@{host}:{port}/{db_name}"

    raise ValueError(f"Unsupported DOCKLINER_DB_TYPE: {settings.DB_TYPE}")


def require_live_vars() -> None:
    """Validate that live database variables are present when DB_MODE=live."""
    # SQLite live mode only needs a path; user/password are not used.
    if (settings.DB_TYPE or "sqlite").lower().strip() == "sqlite":
        return
    missing = []
    if not settings.DB_LIVE_HOST:
        missing.append("DOCKLINER_DB_LIVE_HOST")
    if not settings.DB_LIVE_USER:
        missing.append("DOCKLINER_DB_LIVE_USER")
    if not settings.DB_LIVE_PASSWORD:
        missing.append("DOCKLINER_DB_LIVE_PASSWORD")
    if not settings.DB_LIVE_NAME:
        missing.append("DOCKLINER_DB_LIVE_NAME")
    if missing:
        raise ValueError(
            f"DB_MODE=live with a non-SQLite database requires the following environment variables: {', '.join(missing)}"
        )


def validate_db_config() -> None:
    """Run mode-specific validation. Log issues to why_stuck.log."""
    try:
        mode = resolve_db_mode()
    except Exception as e:
        _log_stuck(f"DB_MODE resolution failed: {e}")
        raise
    try:
        db_type = resolve_db_type(mode)
    except Exception as e:
        _log_stuck(f"DB_TYPE resolution failed: {e}")
        raise
    try:
        if mode == "live":
            require_live_vars()
        if mode == "test" and db_type != "sqlite" and not _has_test_vars():
            raise ValueError(
                "DB_MODE=test with a non-SQLite database requires DOCKLINER_DB_TEST_HOST, "
                "DOCKLINER_DB_TEST_USER, DOCKLINER_DB_TEST_PASSWORD, and DOCKLINER_DB_TEST_NAME"
            )
    except Exception as e:
        _log_stuck(f"DB config validation failed: {e}")
        raise


# ---------------------------------------------------------------------------
# Ensure secret key and env on import
# ---------------------------------------------------------------------------
def _ensure_env_file() -> None:
    """If .env is missing, create a default one using the env refiner and reload settings."""
    env_path = Path(".env")
    if env_path.exists():
        return
    try:
        from app.env_maker import refine_env
        env_path.write_text(refine_env(""), encoding="utf-8")
        _log_stuck(".env was missing. Created default .env from template.")
    except Exception as e:
        _log_stuck(f".env was missing and could not be created: {e}")


def _reload_settings_from_env_file() -> None:
    """Load .env into os.environ so pydantic Settings sees the values."""
    env_path = Path(".env")
    if not env_path.exists():
        return
    try:
        with env_path.open("r", encoding="utf-8") as f:
            for line in f:
                stripped = line.strip()
                if not stripped or stripped.startswith("#") or "=" not in stripped:
                    continue
                key, _, value = stripped.partition("=")
                if key.startswith(_ENV_PREFIX):
                    os.environ[key] = value
    except Exception as e:
        _log_stuck(f"Could not reload .env into environment: {e}")


_ensure_env_file()
_reload_settings_from_env_file()
settings = Settings()  # re-instantiate after env file is guaranteed
_ensure_secret_key()
validate_db_config()


# Parse users JSON
def _load_users():
    import json
    try:
        return json.loads(settings.USERS)
    except Exception:
        _log_stuck(f"Could not parse DOCKLINER_USERS JSON: {settings.USERS[:80]}")
        return []

ALLOWED_USERS = _load_users()

# Ensure dirs exist
Path(settings.PROJECTS_DIR).mkdir(parents=True, exist_ok=True)
Path(settings.DOWNLOADS_DIR).mkdir(parents=True, exist_ok=True)
Path(settings.LOGS_DIR).mkdir(parents=True, exist_ok=True)

def _is_port_configured_explicitly() -> bool:
    """True if the user set DOCKLINER_PORT explicitly in the environment."""
    return f"{_ENV_PREFIX}PORT" in os.environ


def resolve_hosts() -> List[str]:
    """Return the configured host list. Defaults to ['0.0.0.0']."""
    raw = (settings.HOST or "0.0.0.0").strip()
    if not raw:
        return ["0.0.0.0"]
    hosts = [h.strip() for h in raw.split(",") if h.strip()]
    return hosts or ["0.0.0.0"]


def resolve_port() -> int:
    """
    Return the port the app must bind to.

    - If DOCKLINER_PORT is configured and free on every configured host -> use it.
    - If configured but occupied on any host ->
        * strict: raise RuntimeError
        * auto: try DOCKLINER_ALLOWED_PORTS whitelist in order (max 100 attempts),
          write the chosen port to .env, and return it.
    - If not configured:
        * strict: raise a well-organized error.
        * auto: start from default 50021, try whitelist, write chosen port to .env.
    """
    env_port = os.environ.get(f"{_ENV_PREFIX}PORT")
    hosts = resolve_hosts()

    if env_port:
        try:
            port = int(env_port)
        except ValueError:
            _log_stuck(f"DOCKLINER_PORT='{env_port}' is not a valid integer")
            raise RuntimeError(f"DOCKLINER_PORT='{env_port}' is not a valid integer.")
        if not _try_port(hosts, port):
            _log_stuck(f"DOCKLINER_PORT={port} is in use on at least one host among {hosts}")
            selection = (settings.PORT_SELECTION or "strict").lower().strip()
            if selection != "auto":
                raise RuntimeError(
                    f"DOCKLINER_PORT={port} is already in use on one of {','.join(hosts)}. "
                    "Set DOCKLINER_PORT to a free port or set DOCKLINER_PORT_SELECTION=auto."
                )
        else:
            return port

    selection = (settings.PORT_SELECTION or "strict").lower().strip()
    if selection != "auto":
        _log_stuck("DOCKLINER_PORT is not configured and DOCKLINER_PORT_SELECTION=strict")
        raise RuntimeError(
            "DOCKLINER_PORT is not configured. Set DOCKLINER_PORT=<free-port> "
            "or set DOCKLINER_PORT_SELECTION=auto to let DockLiner choose a free port."
        )

    # Auto mode: try whitelist in order, starting from DOCKLINER_PORT if present
    allowed = _allowed_ports()
    start_port = settings.PORT
    start_idx = 0
    if start_port in allowed:
        start_idx = allowed.index(start_port)
    candidates = allowed[start_idx:] + allowed[:start_idx]
    chosen = None
    attempts = 0
    for port in candidates:
        attempts += 1
        if attempts > 100:
            break
        if _try_port(hosts, port):
            chosen = port
            break
        _log_stuck(f"Port {port} is in use on one of {','.join(hosts)}")

    if chosen is None:
        _log_stuck("Could not find a free port in DOCKLINER_ALLOWED_PORTS after 100 attempts")
        raise RuntimeError(
            "Could not find a free port in DOCKLINER_ALLOWED_PORTS. "
            "Free a port from the whitelist or add more ports."
        )

    _write_env_value("PORT", str(chosen))
    os.environ[f"{_ENV_PREFIX}PORT"] = str(chosen)
    _log_stuck(f"Auto-selected free port {chosen} and wrote DOCKLINER_PORT={chosen} to .env")
    print(f"[DockLiner] Auto-selected free port: {chosen}")
    return chosen
